# Generated by Django 2.1.5 on 2019-01-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('accesskey', models.CharField(max_length=32)),
                ('secretkey', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
